version: "3"

services: 
  control_server:
    image: ghcr.io/ipab-rad/lite6_control:rolling
    build: 
      context: ../../
      dockerfile: .docker/control/Dockerfile.control
    devices:
      - "/dev:/dev"
    privileged: true
    network_mode: "host"
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 70
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856
    command: ros2 launch lite6_control_demos control_server.launch.py # replace with command for specific tutorial
    deploy:
      restart_policy: 
        condition: any
      placement:
        constraints:
          - node.hostname == robot

  moveit:
    image: ghcr.io/ipab-rad/lite6_motion_planning:rolling
    build: 
      context: ../../
      dockerfile: .docker/motion_planning/Dockerfile.motion_planning
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${DOCKER_XAUTH}
    volumes:
      - /tmp/.X11-unix:/tml/.X11-unix:rw
      - ${DOCKER_XAUTH}:${DOCKER_XAUTH}
    devices:
      - "/dev:/dev"
    privileged: true
    network_mode: "host"
    command: ros2 launch lite6_moveit_demos motion_planning.launch.py
    deploy:
      placement:
        constraints:
          - node.hostname == robot


  zed2:
    image: ghcr.io/ipab-rad/zed2:rolling
    build: 
      context: ../../
      dockerfile: .docker/cameras/Dockerfile.zed
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - "/dev:/dev"
    privileged: true
    runtime: nvidia
    network_mode: "host"
    command: ros2 launch zed_wrapper zed2i.launch.py
    deploy:
      placement:
        constraints:
          - node.hostname == robot

  foxglove:
    image: ghcr.io/foxglove/studio:latest
    volumes:
      - ../../.foxglove/xarm_joint_positions.json:/foxglove/default-layout.json
    network_mode: "host"
    deploy:
      placement:
        constraints:
          - node.hostname == thor
