camera_info_topic: /zed2i/zed_node/rgb_raw/camera_info
camera_topic: /zed2i/zed_node/rgb_raw/image_raw_color
calibration_service_name: /camera_calibration/run_calibration

num_samples: 3 # for debug purposes
sample_delay: 1.0


charuco:
  squares_x: 14
  squares_y: 9
  square_length: 0.02
  marker_length: 0.015

workspace:
  x_min: 0.3
  x_max: 0.4
  y_min: -0.1
  y_max: 0.1
  z_min: 0.2
  z_max: 0.4 
  rot_x_min: 160.0
  rot_x_max: 200.0
  rot_y_min: -90.0
  rot_y_max: -135.0
  rot_z_min: -5.0
  rot_z_max: 5.0
