version: "3"

services: 
  moveit:
    image: ghcr.io/ipab-rad/lite6_ws:control
    build: 
      context: ../../
      dockerfile: .docker/control/Dockerfile.control
    devices:
      - "/dev:/dev"
    privileged: true
    network_mode: "host"
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 70
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856
    command: ros2 launch lite6_moveit_demos control_server.launch.py # replace with command for specific tutorial
    deploy:
      restart_policy: 
        condition: any
