version: "3"

services: 
  moveit:
    image: ghcr.io/ipab-rad/ufactory_lite6:base
    build: 
      context: ../
      dockerfile: .docker/base_image
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${DOCKER_XAUTH}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${DOCKER_XAUTH}:${DOCKER_XAUTH}
    network_mode: "host"
    privileged: true
    runtime: nvidia
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 70
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856
    command: ros2 launch lite6_moveit_demos jupyter_notebook_prototyping.launch.py

