version: "3"

services: 
  moveit:
    image: ghcr.io/ipab-rad/ufactory_lite6:perception
    build: 
      context: ../
      dockerfile: .docker/perception_image
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${DOCKER_XAUTH}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/.X11-unix:/tml/.X11-unix
      - ${DOCKER_XAUTH}:${DOCKER_XAUTH}
    privileged: true
    devices:
      - "/dev:/dev"
    runtime: nvidia
    network_mode: "host"
    command: ros2 launch xarm_moveit_config lite6_moveit_realmove.launch.py robot_ip:=192.168.1.156 [add_gripper:=true]
