policy:
  sensor1:
    type: {
        type: string,
        default_value: "/sensor_msgs/msg/Image",
        description: "",
      }
    topic: {
        type: string,
        default_value: "/zed2i/zed_node/rgb/image_rect_color",
        description: "",
      }
    qos: {
        type: int,
        default_value: 10,
        description: "",
      }
  
  controller1:
    type: {
        type: string,
        default_value: "/geometry_msgs/msgs/PoseStamped",
        description: "",
      }
    topic: {
        type: string,
        default_value: "/servo_node/pose_target_cmds",
        description: "",
      }
    qos: {
        type: int,
        default_value: 10,
        description: "",
      }

