policy:
  sensors:
    - front_camera:
      type: /sensor_msgs/msg/Image
      topic: /zed2i/zed_node/rgb/image_rect_color
      qos: 10

  controller:
    - eef_pose_controller:
      type: /geometry_msgs/msgs/PoseStamped
      topic: /servo_node/pose_target_cmds
      qos: 10
